# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/ksoclabs/kbom"
  version "0.1.2"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.1.2/kbom_0.1.2_darwin_arm64.tar.gz"
      sha256 "595c895a074c7c83f4d0aa9c894cfda35e8488c1fa8d14ea29e46afd6114cee7"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.1.2/kbom_0.1.2_darwin_amd64.tar.gz"
      sha256 "199fa8b142e598bd574ea5be830c22fae484a6e43f0f9eb808e05fb857a0ff4f"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.1.2/kbom_0.1.2_linux_arm64.tar.gz"
      sha256 "96d1d6aa317edd4ab2f3253825245fc39aba47058d3b16d9580ea4b3395846aa"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.1.2/kbom_0.1.2_linux_amd64.tar.gz"
      sha256 "5492b2f2090495f700d0d6620c622d3f1e696270d9f930942134817443a74809"

      def install
        bin.install "kbom"
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
