# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/ksoclabs/kbom"
  version "0.2.1"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.1/kbom_0.2.1_darwin_arm64.tar.gz"
      sha256 "d8a9b55df5afdf139f579c3eb6cbd3ecd14dacccd69b3ff04b1b489e62cea63c"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.1/kbom_0.2.1_darwin_amd64.tar.gz"
      sha256 "c5574930233f0906ffd0c4aeeeca7a5801d212357471de13761d5c55b00cb900"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.1/kbom_0.2.1_linux_amd64.tar.gz"
      sha256 "0e785faf9fa727cf0c225cbbf02b0a89d324275204fa54a9c725b285b8a6d3a4"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.1/kbom_0.2.1_linux_arm64.tar.gz"
      sha256 "f789b84d440742dc55d41bf7618ab27ed665097af2895ed3412f706e6c990906"

      def install
        bin.install "kbom"
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
