# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/ksoclabs/kbom"
  version "0.2.5"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.5/kbom_0.2.5_darwin_amd64.tar.gz"
      sha256 "568492617dad67db5fe9bab588911997cdc5bff9ea7635b520e05c9200a29208"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.5/kbom_0.2.5_darwin_arm64.tar.gz"
      sha256 "790744102375ab2ade56336012393e829d41559ac472c32335c71f5ae5314088"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.5/kbom_0.2.5_linux_amd64.tar.gz"
      sha256 "df2c1fb824297778b6217195ce14ad29af7d64c003b26d4631f68ad96413ad93"

      def install
        bin.install "kbom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksoclabs/kbom/releases/download/v0.2.5/kbom_0.2.5_linux_arm64.tar.gz"
      sha256 "7d0d39b60af7e1a3033d186099f12a4c51e95bbbb012079557c9fdf4101fa466"

      def install
        bin.install "kbom"
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
